//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCruidEF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        [Display(Name ="First Name")]
        [Required(ErrorMessage ="Enter First Name"),MaxLength(50)]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Enter Last Name"), MaxLength(50)]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Enter Address1"), MaxLength(100)]
        public string Address1 { get; set; }

        public string Address2 { get; set; }

        [Display(Name = "Email address")]
        [Required(ErrorMessage = "The email address is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string EmailID { get; set; }
    }
}
